footer
Oleh-Cheliakh/keyboard-crusaders-team-project pull request #7
Opened 2023-09-20 16:21 UTC by Filip-Povidernyi

Зробив мобільну версію
Зробив планшет
Зробив десктоп
Трабли з іконками соцмереж
не доробив ховер та фокус

2023-09-20 18:24 UTC, Oleh-Cheliakh requested changes
Потрібно переглянути відносний файл до іконок, та скопіювати svg з репозиторію щоб нічого не змінювалось, бо можуть інші іконки в людей поплисти

2023-09-20 18:24 UTC, Oleh-Cheliakh commented on src/partials/footer.html
> +              <use href="./images/icons.svg#icon-instagram"></use>
потрібно змінити відносний шлях до іконок, іконки лежать в img/icons/icons.svg

2023-09-20 18:24 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +.container {
пропоную прибрати правило container воно вже є в base css

2023-09-20 18:24 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +@import url(../css/base.css);
import можна не робити вони вже додані в загальний файл styles.css

2023-09-20 18:24 UTC, Oleh-Cheliakh commented on src/img/icons/icons.svg
скопіюй icons.svg з репозиторію, не бачу що тут змінювалось

2023-09-21 10:53 UTC, Oleh-Cheliakh requested changes
Потрібно доробити посилання на іконки, додати посилання в навігацію та переглянути стилі.

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-style: normal;
фонт стайл прибрати краще, він і так normal за замовчуванням

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    line-height: normal;
і так normal за замовчуванням. line-height - прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    color: #4DC274;
використай var(--green)

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-family: Manrope;
font-family за замовчуванням вказано, це прибрати правило потрібно

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-style: normal;
font-style прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    line-height: normal;
line-height прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    display: block;
address за замовчуванням block element. переглянь будь ласка це

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    margin-top: 0;
в reset.css вже обнулено margin. margin-top тут прибрати потрібно

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-family: Manrope;
font family прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    line-height: 18px;
font-style, font-weight - потрібно прибрати, вони за замовчуванням вказані
line-height обовʼязково вказувати тільки у множнику, бо при зміні розміру тексту текст буде перекриватись шрифт. 
Якщо у figma вказано line-height: 18px; /* 128.571% */
тоді line-height повинно бути 1.29 (за правилом округлення)

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    color: #FFF;
для кольору використовуй var(--white)

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    line-height: 1.3;
краще 1.29

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-family: Manrope;
font-family прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-style: normal;
font-style прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    color: #FFF;
для кольору використовуй var(--white)

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-family: Manrope;
font-family прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    font-style: normal;
font-style прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    line-height: 1.3;
краще 1.29

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +.footer-nav-item {
стилі співпадають з footer-contact, їх краще поєднати або задати цим елементам один клас із загальними стилями, а ті стилі що відрізняються їх оформити в інші класи для цих елементів

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    fill: #FFF;
використовуй var(--white)

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    max-width: 375px;
max-width зазначено у контейнері, це потрібно прибрати

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    margin-top: 0;
margin-top вже був обнулений у reset.css, тут його прибрати потрібно

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +.tos-text {
об'єднай правила з privacy policy, це два однакові елементи

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +    display: flex;
flex зайвий

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/partials/footer.html
> +  <div class="copyrights container">
оформи два посилання списком, це два однорідних елементи

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +        max-width: 768px;
max-width є в контейнері

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +        max-width: 768px;
max-width є в контейнері

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +        padding-top: 16px;
падінги краще використовувати в елементах які огортають контент, margin викоритовувати для відступу одного елемента від іншого за правилом елементи зліва відштовхують елементи справа, а елементи зверху відштовхують елементи знизу. Нижній блок потрібно переглянути

2023-09-21 10:53 UTC, Oleh-Cheliakh commented on src/css/footer.css
> +}
немає правил для desktop при min-width: 1280px

2023-09-21 10:55 UTC, Oleh-Cheliakh requested changes
Потрібно переглянути стилі та html файл відповідно до коментарів

2023-09-22 07:17 UTC, Oleh-Cheliakh requested changes
передивись будь ласка ще раз стилі та верстку, при перегляді заходь у pull requests - files changed, там ти будеш бачити код та коментарі, та одразу зможеш виправляти у себе

2023-09-22 08:21 UTC, Filip-Povidernyi commented on src/css/footer.css
> +    font-style: normal;
не можу прибрати. Address робить текст курсивом.

2023-09-22 08:21 UTC, Filip-Povidernyi commented on src/css/footer.css
> +.tos-text {
Не зовсім розумію, що маєш на увазі. Поясни більш розгорнуто, будь ласка

2023-09-22 08:21 UTC, Filip-Povidernyi commented on src/partials/footer.html
> +  <div class="copyrights container">
теж не зовсім розумію, що маєш на увазі

2023-09-22 08:21 UTC, Filip-Povidernyi commented on src/partials/footer.html
> +      <p class="contact-text tos-text">Terms of Service</p>
На яку сторінку? Зараз перероблю

2023-09-22 08:59 UTC, Oleh-Cheliakh approved these changes
дякую, добре попрацював

2023-09-22 09:00 UTC, merged